parameters:
  - name: deploymentProfile
    type: object
  - name: artifactAlias
    type: string
  - name: artifactName
    type: string
  - name: releaseList
    type: object
  - name: deploymentConfig
    type: object
  - name: apigeeConfigList
    type: object

stages:
  - ${{ each release in parameters.releaseList }}:
      - stage: ${{ release.stageName }}
        displayName: ${{ release.displayName }}
        variables:
          - ${{ each variableGroup in release.variableGroups }}:
              - group: ${{ variableGroup }}
        jobs:
          - template: ../deployment-profiles/${{ parameters.deploymentProfile.type }}/${{ parameters.deploymentProfile.name }}/v${{ parameters.deploymentProfile.version }}.yaml
            parameters:
              deploymentProfile: ${{ parameters.deploymentProfile }}
              artifactAlias: ${{ parameters.artifactAlias }}
              artifactName: ${{ parameters.artifactName }}
              environment: ${{ release.environment }}
              ${{ if and(eq(parameters.deploymentProfile.name, 'mvn-plugins'), eq(parameters.deploymentConfig.customApigeeConfig, 'true')) }}:
                apigeeConfigList: ${{ parameters.apigeeConfigList }}
