parameters:
  - name: buildProfile
    type: object
    default:
      type:
      name:
      version:
  - name: preBuildStageName
    type: string
    default: PreBuild
  - name: preBuildStageDisplayName
    type: string
    default: PreBuild
  - name: buildStageName
    type: string
    default: Build
  - name: buildStageDisplayName
    type: string
    default: Build
  - name: variableGroups
    type: object
    default: []

resources:
  repositories:
    - repository: scripts
      type: github
      name: ShehabEl-DeenAlalkamy/apigee-core-yaml-pipeline-templates
      ref: main
      endpoint: ShehabEl-DeenAlalkamy

extends:
  template: build-profiles/${{ parameters.buildProfile.type }}/${{ parameters.buildProfile.name }}/v.${{ parameters.buildProfile.version }}.yaml
  parameters:
    ${{ each param in parameters }}:
      ${{ param.key }}: ${{ param.value }}
