parameters:
  - name: buildProfile
    type: object

jobs:
  - template: ../jobs/sca.yaml
    parameters:
      buildProfile: ${{ parameters.buildProfile }}

  - ${{ if and(eq(parameters.buildProfile.name, 'mvn-plugins'), eq(parameters.buildProfile.type, 'api-proxies')) }}:
      - template: ../jobs/unit-testing.yaml
